### ISSUE TITLE
Failed to deserialize KDL node

### ISSUE THREAD

**Issue by strophy** [orhun/alpkg#3]
I'm trying to follow the documentation step by step, and the tool successfully created the chroot, cloned my fork of the aports repo and loaded my existing keys. Great! I then tried `alpkg fetch bazel6` which failed halfway through with:
```
  × Failed to parse Zellij configuration
   ╭─[/home/strophy/apkbuilds/pkg-edit-layout.yml:1:1]
 1 │ # https://zellij.dev/old-documentation/layouts.html
   · ─┬
   ·  ╰── Failed to deserialize KDL node. 
Possible reasons:
- Missing `;` after a node name, eg. { node; another_node; }
- Missing quotations (") around an argument node eg. { first_node "argument_node"; }
- Missing an equal sign (=) between node arguments on a title line. eg. argument="value"
- Found an extraneous equal sign (=) between node child arguments and their values. eg. { argument="value" }
 2 │ tabs:
   ╰────
  help: For more information, please see our configuration guide: https://zellij.dev/documentation/configuration.html

```

Is this a configuration error or has something changed? The file exists and seems to contain some YML config for Zellij. Removing the comment at the beginning results in the same error on a different line.

**Comment by orhun** [comment]
Hey! 🐻 

With the new versions of Zellij they switched to a new configuration format. I just pushed eba365fe98467c3b75daa55bda58f3ba8abf8e8d which should fix this.

Can you check and confirm?
